# Generated by Django 4.2 on 2026-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
