# Generated by Django 4.2 on 2026-02-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_roombooking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
