# Generated by Django 4.2 on 2026-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_roombooking_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
