# Generated by Django 4.2 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('classrooms', 'Classrooms'), ('labs', 'Labs'), ('staffrooms', 'Staffrooms'), ('halls', 'Halls'), ('outdoors', 'Outdoors'), ('washrooms', 'Washrooms'), ('officerooms', 'Officerooms'), ('others', 'Others')], default='classrooms', max_length=20),
        ),
    ]
