# Generated by Django 4.2 on 2026-02-20 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_issue_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBookingCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='roombooking',
            name='requirements_doc',
            field=models.FileField(blank=True, help_text='Upload a Word document or leave empty if Not Applicable.', null=True, upload_to='room_bookings/requirements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
    ]
