# Generated by Django 4.2 on 2026-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_department_name'),
        ('inventory', '0004_alter_room_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevertedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_email', models.EmailField(max_length=254)),
                ('deleted_user_name', models.CharField(max_length=255)),
                ('reverted_on', models.DateTimeField(auto_now_add=True)),
                ('reassigned_on', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('previous_incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_rooms', to='core.userprofile')),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_rooms', to='core.userprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
            ],
            options={
                'unique_together': {('room', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='RevertedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_email', models.EmailField(max_length=254)),
                ('deleted_user_name', models.CharField(max_length=255)),
                ('reverted_on', models.DateTimeField(auto_now_add=True)),
                ('reassigned_on', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('previous_assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_items', to='core.userprofile')),
                ('previous_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_items_previous', to='inventory.room')),
                ('reassigned_to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_items_reassigned', to='inventory.room')),
                ('reassigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_items', to='core.userprofile')),
            ],
            options={
                'unique_together': {('item', 'organisation')},
            },
        ),
    ]
