# Generated by Django 4.2 on 2026-04-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_department_department_name"),
        ("inventory", "0005_revertedroom_reverteditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="approved_by_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="approved_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="recommended_by_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="recommended_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="rooms",
            field=models.ManyToManyField(blank=True, related_name="multi_room_bookings", to="inventory.room"),
        ),
        migrations.AddField(
            model_name="roombookingrequest",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_booking_requests", to="core.userprofile"),
        ),
        migrations.AddField(
            model_name="roombookingrequest",
            name="approved_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roombookingrequest",
            name="recommended_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roombookingrequest",
            name="rooms",
            field=models.ManyToManyField(blank=True, related_name="multi_room_booking_requests", to="inventory.room"),
        ),
    ]
