# Generated by Django 4.2 on 2026-04-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_department_name'),
        ('inventory', '0006_room_booking_multi_room_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookingrequest',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_bookings', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='workflow_stage',
            field=models.CharField(choices=[('sub_admin', 'Sub Admin Review'), ('central_admin', 'Central Admin Final Approval')], default='sub_admin', max_length=20),
        ),
    ]
