# Generated by Django 4.2 on 2025-03-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_roomsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='inventory.purchase'),
        ),
    ]
