# Generated by Django 4.2 on 2026-02-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockrequest_remove_item_is_edit_lock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
        migrations.AlterField(
            model_name='category',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
