# Generated by Django 4.2 on 2025-06-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0007_alter_receipt_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_incharge', to='core.userprofile'),
        ),
    ]
