# Generated by Django migration for RoomBookingEditRequest model

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_roombookingrequest_recommended_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBookingEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_email', models.EmailField()),
                ('original_start_datetime', models.DateTimeField()),
                ('original_end_datetime', models.DateTimeField()),
                ('original_purpose', models.TextField(blank=True, null=True)),
                ('new_start_datetime', models.DateTimeField()),
                ('new_end_datetime', models.DateTimeField()),
                ('new_purpose', models.TextField(blank=True, null=True)),
                ('new_requirements_doc', models.FileField(blank=True, null=True, upload_to='room_booking_edits/requirements/')),
                ('new_requirements_text', models.TextField(blank=True, help_text='Plain text requirements typed by faculty for edited booking.', null=True)),
                ('changes_made', models.JSONField(default=dict, help_text='Stores what fields were changed for highlighting in approval cards')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tat_deadline', models.DateTimeField(blank=True, help_text='Deadline by which admin must approve/reject.', null=True)),
                ('workflow_stage', models.CharField(choices=[('sub_admin', 'Sub Admin Review'), ('central_admin', 'Central Admin Final Approval')], default='sub_admin', max_length=20)),
                ('recommended_note', models.TextField(blank=True)),
                ('approved_note', models.TextField(blank=True)),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='inventory.roombooking')),
                ('original_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_edit_requests', to='core.department')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_edit_requests', to='core.department')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edit_requests', to='core.userprofile')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_edit_requests', to='core.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='roombookingeditrequest',
            name='new_rooms',
            field=models.ManyToManyField(blank=True, related_name='new_edit_requests', to='inventory.room'),
        ),
        migrations.AddField(
            model_name='roombookingeditrequest',
            name='original_rooms',
            field=models.ManyToManyField(blank=True, related_name='original_edit_requests', to='inventory.room'),
        ),
    ]
