# Generated by Django 4.2 on 2026-02-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_is_sub_admin'),
        ('inventory', '0007_alter_brand_room_alter_category_room_alter_item_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for purchase request'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_made', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor'),
        ),
    ]
