# Generated by Django 4.2 on 2026-04-30 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_roombooking_status_cancelled_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='requirements_doc',
            field=models.FileField(blank=True, help_text='Upload a PDF or image file, or leave empty if Not Applicable.', null=True, upload_to='room_bookings/requirements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'heic', 'heif', 'webp', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='requirements_doc',
            field=models.FileField(blank=True, null=True, upload_to='room_booking_requests/requirements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'heic', 'heif', 'webp', 'gif', 'bmp', 'tiff', 'tif'])]),
        ),
    ]
