# Generated by Django 4.2 on 2026-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchase_reason_purchase_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='requirements_doc_text',
            field=models.TextField(blank=True, help_text='Auto-extracted plain text from the uploaded requirements document.', null=True),
        ),
    ]
