# Generated by Django 4.2 on 2026-04-25 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_department_name'),
        ('inventory', '0008_room_booking_edit_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookingeditrequest',
            name='new_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_edit_requests', to='core.department'),
        ),
        migrations.AlterField(
            model_name='roombookingeditrequest',
            name='new_requirements_doc',
            field=models.FileField(blank=True, null=True, upload_to='room_booking_edits/requirements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='roombookingeditrequest',
            name='original_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_edit_requests', to='core.department'),
        ),
    ]
