# Generated by Django 4.2 on 2026-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item_brand',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item_category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
