# Generated by Django 4.2 on 2025-09-28 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchase_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_model_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='arrival_receipts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='closing_balance_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='consumed_stock_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_of_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='opening_stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_stock',
            field=models.FloatField(default=0),
        ),
    ]
