# Generated by Django 4.2 on 2026-03-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_is_sub_admin'),
        ('inventory', '0011_purchase_item_brand_purchase_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete'), ('bulk_delete', 'Bulk Delete')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('record_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_performed', to='core.userprofile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
