# Generated by Django 4.2 on 2026-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_issue_incharge_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='add_return_note',
            field=models.TextField(blank=True, help_text='Internal admin note for extra items added/taken or returned for this booking. Not emailed.', null=True),
        ),
    ]
