# Generated by Django 4.2 on 2026-03-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
