# Generated by Django 4.2 on 2025-11-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0012_item_cost_item_vendor_item_warranty_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='escalation_level',
            field=models.IntegerField(default=0, help_text='0=room_incharge, 1=sub_admin, 2=central_admin'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter_email',
            field=models.EmailField(blank=True, help_text='Reporter college email (must be @sfscollege.in)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='tat_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.CharField(blank=True, help_text='Reporter name or identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
