# Generated by Django 4.2 on 2026-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_issue_closure_reason_delete_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='requirements_text',
            field=models.TextField(blank=True, help_text='Plain text requirements entered directly by the faculty.', null=True),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='reminder_12h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='requirements_text',
            field=models.TextField(blank=True, help_text='Plain text requirements typed by faculty (no document upload needed).', null=True),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='tat_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline by which admin must approve/reject. Auto-cancelled if exceeded.', null=True),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired / Auto-Cancelled')], default='pending', max_length=20),
        ),
    ]
