# Generated by Django 4.2 on 2026-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_roombooking_requirements_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcomponent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('disposed', 'Disposed')], default='active', max_length=20),
        ),
    ]
