# Generated by Django 4.2 on 2025-11-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_editrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditRequest',
        ),
    ]
