# Generated by Django 4.2 on 2026-03-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_systemcomponent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='status',
        ),
    ]
