# Generated by Django 4.2 on 2026-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_item_active_inactive_archive_category_itemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
