# Generated by Django 4.2 on 2025-11-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_is_sub_admin'),
        ('inventory', '0016_item_created_by_editrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='proposed_data',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='editrequest',
            name='changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edits', to='core.userprofile'),
        ),
    ]
