# Generated by Django 4.2 on 2025-11-29 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0017_remove_editrequest_proposed_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='reviewed_on',
        ),
        migrations.AddField(
            model_name='item',
            name='is_edit_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
