# Generated by Django 4.2 on 2026-03-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_item_product_code_assettag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='inventory.system')),
            ],
        ),
    ]
