# Generated by Django 4.2 on 2025-12-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_editrequest_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='proposed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
