# Generated by Django 4.2 on 2026-05-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_issueremark'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issueremark',
            index=models.Index(fields=['issue', 'created_at'], name='inventory_i_issue_i_021bc0_idx'),
        ),
    ]
