# Generated by Django 4.2 on 2025-12-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_is_sub_admin'),
        ('inventory', '0019_editrequest_proposed_data_editrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_edit_requests', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter_email',
            field=models.EmailField(blank=True, help_text='Reporter college email (@sfscollege.in)', max_length=255, null=True),
        ),
    ]
