# Generated by Django 4.2 on 2025-12-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_editrequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
    ]
