# Generated by Django 4.2.29 on 2026-05-21 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_item_is_serviceable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Alternate number must be exactly 10 digits (numbers only).', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits (numbers only).', regex='^\\d{10}$')]),
        ),
    ]
