# Generated by Django 4.2 on 2026-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_vendor_alternate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
