# Generated by Django 4.2 on 2026-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockrequest_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsettings',
            name='archives_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='configurations_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='issues_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='notifications_tab',
            field=models.BooleanField(default=True),
        ),
    ]
