# Generated by Django 6.0.4 on 2026-05-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_booking_email_and_more'),
        ('inventory', '0023_roomsettings_archives_tab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated', to='core.userprofile'),
        ),
    ]
