# Generated by Django 4.2 on 2026-05-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_item_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='approved_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
