# Generated by Django 4.2 on 2026-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_stockrequest_approved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_by_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
