# Generated by Django 6.0.4 on 2026-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_item_updated_by_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='alternative_slots',
            field=models.TextField(blank=True, default='[]', help_text="JSON list of alternative date-time slots. E.g. [{'start': '...', 'end': '...'}]", null=True),
        ),
        migrations.AddField(
            model_name='roombookingrequest',
            name='alternative_slots',
            field=models.TextField(blank=True, default='[]', help_text="JSON list of alternative date-time slots. E.g. [{'start': '...', 'end': '...'}]", null=True),
        ),
    ]
