# Generated by Django 4.2 on 2025-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_sub_admin',
            field=models.BooleanField(default=False, verbose_name='is sub admin'),
        ),
    ]
