# Generated by Django 4.2 on 2025-11-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_is_sub_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_student',
        ),
    ]
