# Generated by Django 4.2 on 2026-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_udpated_on_department_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='booking_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='booking_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
