# Generated by Django 4.2 on 2026-05-27

from django.db import migrations
import os

def setup_allauth_site_and_app(apps, schema_editor):
    try:
        Site = apps.get_model('sites', 'Site')
        SocialApp = apps.get_model('socialaccount', 'SocialApp')
    except LookupError:
        # If the apps are not in INSTALLED_APPS, do nothing
        return

    domain = 'blixtro.sfscollege.app'
    name = 'Blixtro'

    # Try to find a Site with the desired domain first
    site = Site.objects.filter(domain=domain).first()

    if not site:
        # If not found, get or create Site with ID 1
        site, created = Site.objects.get_or_create(
            id=1,
            defaults={
                'domain': domain,
                'name': name
            }
        )
        if not created:
            # Only update if no other site has this domain (safety check)
            if not Site.objects.filter(domain=domain).exclude(id=site.id).exists():
                site.domain = domain
                site.name = name
                site.save()
    else:
        site.name = name
        site.save()

    # Create or update a Google SocialApp using environment variables or placeholders
    client_id = os.environ.get('GOOGLE_CLIENT_ID', 'placeholder-google-client-id')
    secret = os.environ.get('GOOGLE_CLIENT_SECRET', 'placeholder-google-secret')

    social_app, app_created = SocialApp.objects.get_or_create(
        provider='google',
        defaults={
            'name': 'Google OAuth',
            'client_id': client_id,
            'secret': secret,
        }
    )
    if not app_created:
        if social_app.client_id == 'placeholder-google-client-id' or not social_app.client_id:
            social_app.client_id = client_id
            social_app.secret = secret
            social_app.save()

    # Ensure the social app is associated with the Site
    social_app.sites.add(site)


def rollback_allauth_site_and_app(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_booking_email_and_more'),
        ('sites', '0002_alter_domain_unique'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(setup_allauth_site_and_app, rollback_allauth_site_and_app),
    ]
