# Generated by Django 4.2 on 2025-11-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_sub_admin',
        ),
    ]
