# Generated by Django 4.2 on 2025-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_is_sub_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_sub_admin',
            field=models.BooleanField(default=False, verbose_name='is sub admin'),
        ),
    ]
